### ISSUE TITLE
Wallet not working iOS

### ISSUE THREAD

**Issue by claytucker** [Bit-Nation/BITNATION-Pangea-mobile#345] opened 2018-04-12 21:21 UTC
## Feature / Issue
>  I downloaded the app in iOS and it opens fine in Testflight.

## Acceptance criteria
- [ ] When I click on create wallet it opens an instruction page but will not scroll and will not allow me to create a wallet. 

## Additional information
I was trying to get a wallet so that I could receive the air drop for citizens. I have been a citizen since last year. The bug prevented me from creating a wallet in time for the drop. Do I have any alternatives? The Telegram channel referred me here. Thanks.

**Comment by florianlenz** [comment] 2018-05-02 17:41
can you add a screenshot?

**Comment by claytucker** [comment] 2018-05-02 17:49
![img_4404](https://user-images.githubusercontent.com/25402788/39540057-92d5990c-4e0f-11e8-98bf-c23027d7e7fa.PNG)

This screen is static and will not scroll down.

**Comment by seland** [comment] 2018-07-19 21:37
Thanks for reporting. That part of the app was changed, so there is no such screen in the app. Similar screen are scrollable, so the issue is not reproduced anymore, I'm closing the issue. Feel free to reopen in case you have it again.

**Closed by seland** 2018-07-19 21:37 UTC
