### ISSUE TITLE
UI: Chips components for Chat

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#503] opened 2018-09-04 19:38 UTC
## Feature / Issue
> To start a new chat, we need to choose people from a list.
> When a person is chosen, their name appears as a "chip", a Material Design component. (see bottom of this issue for URL and details.)
> We need working "Input Chips"

## Acceptance criteria
- [ ] Styled chip component, with functionality for "cancel"

## Additional information
Here are the detailed spec's on chips! This will give you pixel measurements, states, etc. — everything you need.
See the section on Input Chips: placement, to see stacked chips.

https://material.io/design/components/chips.html#specs

**Comment by seland** [comment] 2018-09-05 18:13
Accidentally created a duplicate of that - #505. However, since we're going to use library instead of implementing it ourselves, I'm closing that issue in favor of new one.

**Closed by seland** 2018-09-05 18:13 UTC
Labels: To Do
