### ISSUE TITLE
[dev] Red screen while testing

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#184] opened 2018-02-09 18:31 UTC
## Feature / Issue
> Hot Reloading does not work in iOS simulator.
> The reloader apparently tries to reload a constant?
> This makes debugging the interface much slower!

## Acceptance criteria
- [x] Make it stop! Make it stop!

## Additional information
![screen shot 2018-02-09 at 10 22 16 am](https://user-images.githubusercontent.com/30195/36043512-672e2ab0-0d84-11e8-8411-b4ad08033f51.jpg)

**Comment by seland** [comment] 2018-02-12 17:38
@mimetic I couldn't reproduce your crash, but I think I fix it, please check feature/ui_0.3.2 branch.

**Comment by seland** [comment] 2018-02-15 22:15
Closed by #191.

**Closed by seland** 2018-02-15 22:15 UTC
Labels: bug
