### ISSUE TITLE
Find nation in old wallet

### ISSUE THREAD

**Issue by cocioale** [Bit-Nation/BITNATION-Pangea-mobile#411] opened 2018-06-14 14:41 UTC
Hello, I made the mistake of installing the new version App without uninstalling the old one, the Seed I put them back, but I do not see Eth and especially the nation that I did.

I wrote the problem in chat.

in chat @Experimentalist wrote me that I should do another Nation (always named Trieste) and then the developers help me to fix the problem. I would not like to create useless double Nations.

I managed to restore the old wallet and now I see my Eth, I see the Trieste nation inside, but not on the first screen. I leave you the screeshot attached.

Do I have to do some particular procedure? type: disassemble the old App. and I install the new one with the same Seed? do I proceed like this?

Thank you

![photo_2018-06-14_16-36-13](https://user-images.githubusercontent.com/10105681/41419191-b3f45a84-6ff1-11e8-9950-c113ee4fbc05.jpg)
![photo_2018-06-14_16-36-19](https://user-images.githubusercontent.com/10105681/41419193-b4257646-6ff1-11e8-87ff-c407cd25f10f.jpg)
![photo_2018-06-14_16-36-35](https://user-images.githubusercontent.com/10105681/41419194-b45ccfe2-6ff1-11e8-9ea5-a661eb6b20d3.jpg)

In chat someone  wrote
## Feature / Issue
> As a user ... (remove this)

## Acceptance criteria
- [ ] When i ... then ... (remove this)

## Additional information
Keep ... in mind

**Comment by seland** [comment] 2018-07-19 21:49
@cocioale The list on dashboard shows only 5 newest nation, so the reason of why you can't see it there is that it's not one of the 5 latest created nations. So, it's an expected behavior. I'll close the issue, feel free to reopen it in case you have some details.

**Closed by seland** 2018-07-19 21:49 UTC
