### ISSUE TITLE
Wallet doesn't work

### ISSUE THREAD

**Issue by cryptohakka** [Bit-Nation/BITNATION-Pangea-mobile#320] opened 2018-03-22 14:48 UTC
## Feature / Issue
Wallet doesn't work if you use old version of this app and update it to newest version.
This problem can be solved if you re-install newest app.

**Comment by NetScr1be** [comment] 2018-03-24 14:55
I have the newest version. Can't create wallet. Words stay blank. Will reinstall and return then update.

**Comment by seland** [comment] 2018-07-19 20:55
@NetScr1be The issue you described was [already reported](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/issues/277) and fixed. Please check out the answer.

**Comment by seland** [comment] 2018-07-19 21:00
@cryptohakka We changed wallet and key part significantly in the latest releases, so it's likely that issue fixed, because we can't reproduce it. I'm closing the issue, in case you have it again, feel free to reopen.

**Closed by seland** 2018-07-19 21:00 UTC
