### ISSUE TITLE
I created the nation but it is not identified as mine 

### ISSUE THREAD

**Issue by dgrtg** [Bit-Nation/BITNATION-Pangea-mobile#353] opened 2018-04-24 00:10 UTC
## Feature / Issue
> As a user ... I created the nation "O Estaleiro" but it is not identified as mine when I click on "My Nations"

## Acceptance criteria
- [ ] When i ... then ... (remove this)

## Additional information
![2018-04-23 20 51 33](https://user-images.githubusercontent.com/14337417/39159193-a17f1496-473a-11e8-946d-62293c06fc73.jpg)
![2018-04-23 20 51 22](https://user-images.githubusercontent.com/14337417/39159194-a1a77d82-473a-11e8-850b-1b1c076fb59f.jpg)

**Comment by seland** [comment] 2018-10-17 19:07
@dgrtg Current nations implementation differentiates between nation ownership and nation membership. "My nations" are only nations that you've joined. However, it's likely going to be changed in the future.
I'm going to close the issue, since it's an expected behavior for currently implemented functionality, even though it may be confusing at the moment.

@borjantrajanoski Should we create separate issue for nation related architectural issues?

**Closed** 2019-03-14 04:07 UTC
