### ISSUE TITLE
[wallet] Restore wallet

### ISSUE THREAD

**Issue by manelomanu** [Bit-Nation/BITNATION-Pangea-mobile#285] opened 2018-03-11 10:52 UTC
## Feature / Issue
> As a user when I update the wallet to the last version

## Acceptance criteria
- and I want to restore the wallet, once I put the words I press "Done" and nothing happens, then I uninstall the wallet, do the same process of giving my words to restore the wallet and press "done"the it works

## Additional information
Keep ... in mind

**Comment by seland** [comment] 2018-07-19 20:46
That part of the app was significantly changed since the issue is reported. I'm closing it, feel free to reopen in case you have it on new versions (0.5.3 and higher).

**Closed by seland** 2018-07-19 20:46 UTC
Labels: bug
