### ISSUE TITLE
When verifying/entering recovery seed of new wallet, please trim the text box input strings

### ISSUE THREAD

**Issue by Mnuzz** [Bit-Nation/BITNATION-Pangea-mobile#316] opened 2018-03-21 13:59 UTC
## Feature / Issue
This occurs when verifying the recovery seed of a new wallet. When clicking a box to type in, there is often a trailing space character. This can cause the app to think that the recovery seed is wrong. This should be done on both the verification, and the actual recovery process. Use the string trim function to remove leading and trailing whitespace. 

## Additional information
I am using a Samsung Galaxy Note 4, Android 6.0.1.

**Comment by florianlenz** [comment] 2018-04-12 07:37
@swmd would you mind to fix this? For the next release it's ok to just remove the white spaces when sending the mnemonic to the pangea lib's function. Another point, could you pleas make sure that all work's are transformed to lower case? All words from bip32 are lowercase, so we can just make sure that they are all lowercase, in case someone enters "House" instead of "house".

**Comment by swmd** [comment] 2018-04-12 17:04
@florianlenz I guess that this issue has been fixed already. I have tested with the latest version and could not reproduce the issue.

**Comment by seland** [comment] 2018-07-19 20:52
Yes, it was fixed in 0.4.0. Closing the issue.

**Closed by seland** 2018-07-19 20:52 UTC
Labels: bug
